version: '3'
services:
  server1:
    image: ads:lab
    build:
      context: .
    container_name: server1
    # ports:
    #   - "1111:1111"
    volumes:
      - ./stockprice_server:/app
    networks:
      - mynetwork
    command: python /app/server.py 

  server2:
    image: ads:lab
    build:
      context: .
    container_name: server2
    # ports:
    #   - "1111:1111"
    volumes:
      - ./stockprice_server:/app
    networks:
      - mynetwork
    command: python /app/server.py  8087  

  server3:
    image: ads:lab
    build:
      context: .
    container_name: server3
    # ports:
    #   - "1111:1111"
    volumes:
      - ./stockprice_server:/app
    networks:
      - mynetwork
    command: python /app/server.py  8087    
  
  client1:
    image: ads:lab
    build:
      context: .
    container_name: client1
    depends_on:
      - nginx
    volumes:
      - ./stockprice_client:/app
    networks:
      - mynetwork
    command: python /app/client.py 8087

  nginx:
    image: nginx:latest
    ports:
      - "8087:8087"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - server1 
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge